<!-- You can include here CSS and Java client side scripts common to all pages -->

<STYLE>   
   <!--
   TD.Top  {
   	vertical-align : top;
   	font-size : x-small;
   }
   
   B.Bolder {
   	FONT-WEIGHT: 900
   }

  .wordsglow {font:Arial; font-size:8pt;  
             color:white; position:absolute; cursor:hand; 
             filter:glow(color=blue,strength=2,enabled=0);
             behavior:url(wordsbehav.sct); }

   A.NoLine:visited { text-decoration:none; color:black }
   A.NoLine:link { text-decoration:none; color:black }
   
   -->
   </STYLE>
   
