<html>
<meta http-equiv="Page-Enter" 
content="revealTrans(Duration=1.0,Transition=23)">
<meta http-equiv="Page-Exit" 
content="revealTrans(Duration=1.0,Transition=23)">
<head>
	<title><% =msPageTitle %> - <% = Application("HCF_NAME") %></title>
	<!-- #INCLUDE FILE="head.inc" -->
</head>

<body>

<TABLE WIDTH="100%" BORDER="0" CELLSPACING="0" CELLPADDING="0" VALIGN="TOP" HEIGHT="100%">

<TR>

<!-- #INCLUDE FILE="top.inc" -->
<!-- #INCLUDE FILE="leftbar.inc" -->

<TD WIDTH="100%" VALIGN="TOP">
<TABLE WIDTH="100%" HEIGHT="100%" VALIGN="TOP"><TR><TD VALIGN="TOP">
<!-- Main Body -->

	<TABLE WIDTH="100%" CELLSPACING="0" CELLPADDING="0" ALIGN="LEFT" VALIGN="TOP">
	<!-- #INCLUDE FILE="pageheading.inc" -->
		
	<!-- Main content -->	
	<TR><TD ALIGN="CENTER" VALIGN="TOP">
	&nbsp;<BR>
	
