	<TR><TD BGCOLOR="Blue">
		<TABLE WIDTH="100%" HIEGHT=0% BORDER="0" ><TR>
		<TD ALIGN="LEFT" VALIGN="MIDDLE" BGCOLOR="Blue"><FONT FACE="MS Sans Serif" SIZE="1" COLOR="White"><B><% = msWindowCaption %></B></FONT></TD>
		<TD ALIGN="RIGHT" BGCOLOR="Blue" VALIGN="MIDDLE">
		<% If mbShowCloseButton = True Then %>
			<A HREF="logout.asp"><IMG SRC="close.gif" WIDTH=16 HEIGHT=14 BORDER=0 TITLE="Logout" ALT="X" ALIGN="RIGHT"></A>
		<% End If %>
		</TD>
		</TR></TABLE>
	</TD></TR>
